/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9-dev */

#include "agent.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(vaccel_VaccelEmpty, vaccel_VaccelEmpty, AUTO)


PB_BIND(vaccel_VaccelRequest, vaccel_VaccelRequest, 2)


PB_BIND(vaccel_VaccelResponse, vaccel_VaccelResponse, 2)




