/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9-dev */

#ifndef PB_VACCEL_AGENT_PB_H_INCLUDED
#define PB_VACCEL_AGENT_PB_H_INCLUDED
#include <pb.h>
#include "session.pb.h"
#include "resources.pb.h"
#include "image.pb.h"
#include "tensorflow.pb.h"
#include "torch.pb.h"
#include "genop.pb.h"
#include "profiling.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _vaccel_VaccelFunctionType {
    vaccel_VaccelFunctionType_UNUSED = 0,
    vaccel_VaccelFunctionType_CREATE_SESSION = 1,
    vaccel_VaccelFunctionType_UPDATE_SESSION = 2,
    vaccel_VaccelFunctionType_DESTROY_SESSION = 3,
    vaccel_VaccelFunctionType_CREATE_RESOURCE = 4,
    vaccel_VaccelFunctionType_REGISTER_RESOURCE = 5,
    vaccel_VaccelFunctionType_UNREGISTER_RESOURCE = 6,
    vaccel_VaccelFunctionType_DESTROY_RESOURCE = 7,
    vaccel_VaccelFunctionType_IMAGE_CLASSIFICATION = 8,
    vaccel_VaccelFunctionType_TENSORFLOW_MODEL_LOAD = 9,
    vaccel_VaccelFunctionType_TENSORFLOW_MODEL_UNLOAD = 10,
    vaccel_VaccelFunctionType_TENSORFLOW_MODEL_RUN = 11,
    vaccel_VaccelFunctionType_TORCH_JITLOAD_FORWARD = 12,
    vaccel_VaccelFunctionType_GENOP = 13,
    vaccel_VaccelFunctionType_GET_TIMERS = 14,
    vaccel_VaccelFunctionType_VACCEL_FUNCTION = 15
} vaccel_VaccelFunctionType;

/* Struct definitions */
typedef struct _vaccel_VaccelEmpty {
    char dummy_field;
} vaccel_VaccelEmpty;

typedef struct _vaccel_VaccelRequest {
    vaccel_VaccelFunctionType function_type;
    pb_size_t which_function_args;
    union {
        vaccel_CreateSessionRequest CreateSessionRequest;
        vaccel_UpdateSessionRequest UpdateSessionRequest;
        vaccel_DestroySessionRequest DestroySessionRequest;
    } function_args;
} vaccel_VaccelRequest;

typedef struct _vaccel_VaccelResponse {
    vaccel_VaccelFunctionType function_type;
    pb_size_t which_function_args;
    union {
        vaccel_CreateSessionResponse CreateSessionResponse;
        vaccel_UpdateSessionResponse UpdateSessionResponse;
        vaccel_DestorySessionResponse DestroySessionResponse;
    } function_args;
} vaccel_VaccelResponse;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _vaccel_VaccelFunctionType_MIN vaccel_VaccelFunctionType_UNUSED
#define _vaccel_VaccelFunctionType_MAX vaccel_VaccelFunctionType_VACCEL_FUNCTION
#define _vaccel_VaccelFunctionType_ARRAYSIZE ((vaccel_VaccelFunctionType)(vaccel_VaccelFunctionType_VACCEL_FUNCTION+1))


#define vaccel_VaccelRequest_function_type_ENUMTYPE vaccel_VaccelFunctionType

#define vaccel_VaccelResponse_function_type_ENUMTYPE vaccel_VaccelFunctionType


/* Initializer values for message structs */
#define vaccel_VaccelEmpty_init_default          {0}
#define vaccel_VaccelRequest_init_default        {_vaccel_VaccelFunctionType_MIN, 0, {vaccel_CreateSessionRequest_init_default}}
#define vaccel_VaccelResponse_init_default       {_vaccel_VaccelFunctionType_MIN, 0, {vaccel_CreateSessionResponse_init_default}}
#define vaccel_VaccelEmpty_init_zero             {0}
#define vaccel_VaccelRequest_init_zero           {_vaccel_VaccelFunctionType_MIN, 0, {vaccel_CreateSessionRequest_init_zero}}
#define vaccel_VaccelResponse_init_zero          {_vaccel_VaccelFunctionType_MIN, 0, {vaccel_CreateSessionResponse_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define vaccel_VaccelRequest_function_type_tag   1
#define vaccel_VaccelRequest_CreateSessionRequest_tag 2
#define vaccel_VaccelRequest_UpdateSessionRequest_tag 3
#define vaccel_VaccelRequest_DestroySessionRequest_tag 4
#define vaccel_VaccelResponse_function_type_tag  1
#define vaccel_VaccelResponse_CreateSessionResponse_tag 2
#define vaccel_VaccelResponse_UpdateSessionResponse_tag 3
#define vaccel_VaccelResponse_DestroySessionResponse_tag 4

/* Struct field encoding specification for nanopb */
#define vaccel_VaccelEmpty_FIELDLIST(X, a) \

#define vaccel_VaccelEmpty_CALLBACK NULL
#define vaccel_VaccelEmpty_DEFAULT NULL

#define vaccel_VaccelRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    function_type,     1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (function_args,CreateSessionRequest,function_args.CreateSessionRequest),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (function_args,UpdateSessionRequest,function_args.UpdateSessionRequest),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (function_args,DestroySessionRequest,function_args.DestroySessionRequest),   4)
#define vaccel_VaccelRequest_CALLBACK NULL
#define vaccel_VaccelRequest_DEFAULT NULL
#define vaccel_VaccelRequest_function_args_CreateSessionRequest_MSGTYPE vaccel_CreateSessionRequest
#define vaccel_VaccelRequest_function_args_UpdateSessionRequest_MSGTYPE vaccel_UpdateSessionRequest
#define vaccel_VaccelRequest_function_args_DestroySessionRequest_MSGTYPE vaccel_DestroySessionRequest

#define vaccel_VaccelResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    function_type,     1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (function_args,CreateSessionResponse,function_args.CreateSessionResponse),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (function_args,UpdateSessionResponse,function_args.UpdateSessionResponse),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (function_args,DestroySessionResponse,function_args.DestroySessionResponse),   4)
#define vaccel_VaccelResponse_CALLBACK NULL
#define vaccel_VaccelResponse_DEFAULT NULL
#define vaccel_VaccelResponse_function_args_CreateSessionResponse_MSGTYPE vaccel_CreateSessionResponse
#define vaccel_VaccelResponse_function_args_UpdateSessionResponse_MSGTYPE vaccel_UpdateSessionResponse
#define vaccel_VaccelResponse_function_args_DestroySessionResponse_MSGTYPE vaccel_DestorySessionResponse

extern const pb_msgdesc_t vaccel_VaccelEmpty_msg;
extern const pb_msgdesc_t vaccel_VaccelRequest_msg;
extern const pb_msgdesc_t vaccel_VaccelResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define vaccel_VaccelEmpty_fields &vaccel_VaccelEmpty_msg
#define vaccel_VaccelRequest_fields &vaccel_VaccelRequest_msg
#define vaccel_VaccelResponse_fields &vaccel_VaccelResponse_msg

/* Maximum encoded size of messages (where known) */
#define VACCEL_AGENT_PB_H_MAX_SIZE               vaccel_VaccelRequest_size
#define vaccel_VaccelEmpty_size                  0
#define vaccel_VaccelRequest_size                16
#define vaccel_VaccelResponse_size               10

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
