/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9-dev */

#ifndef PB_VACCEL_GENOP_PB_H_INCLUDED
#define PB_VACCEL_GENOP_PB_H_INCLUDED
#include <pb.h>
#include "error.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _vaccel_GenopArg {
    uint32_t argtype;
    uint32_t size;
    pb_callback_t buf;
} vaccel_GenopArg;

typedef struct _vaccel_GenopRequest {
    uint32_t session_id;
    pb_callback_t read_args;
    pb_callback_t write_args;
} vaccel_GenopRequest;

typedef struct _vaccel_GenopResult {
    pb_callback_t write_args;
} vaccel_GenopResult;

typedef struct _vaccel_GenopResponse {
    pb_size_t which_result;
    union {
        vaccel_VaccelError error;
        vaccel_GenopResult genop_result;
    } result;
} vaccel_GenopResponse;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define vaccel_GenopArg_init_default             {0, 0, {{NULL}, NULL}}
#define vaccel_GenopRequest_init_default         {0, {{NULL}, NULL}, {{NULL}, NULL}}
#define vaccel_GenopResult_init_default          {{{NULL}, NULL}}
#define vaccel_GenopResponse_init_default        {0, {vaccel_VaccelError_init_default}}
#define vaccel_GenopArg_init_zero                {0, 0, {{NULL}, NULL}}
#define vaccel_GenopRequest_init_zero            {0, {{NULL}, NULL}, {{NULL}, NULL}}
#define vaccel_GenopResult_init_zero             {{{NULL}, NULL}}
#define vaccel_GenopResponse_init_zero           {0, {vaccel_VaccelError_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define vaccel_GenopArg_argtype_tag              1
#define vaccel_GenopArg_size_tag                 2
#define vaccel_GenopArg_buf_tag                  3
#define vaccel_GenopRequest_session_id_tag       1
#define vaccel_GenopRequest_read_args_tag        2
#define vaccel_GenopRequest_write_args_tag       3
#define vaccel_GenopResult_write_args_tag        1
#define vaccel_GenopResponse_error_tag           1
#define vaccel_GenopResponse_genop_result_tag    2

/* Struct field encoding specification for nanopb */
#define vaccel_GenopArg_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   argtype,           1) \
X(a, STATIC,   SINGULAR, UINT32,   size,              2) \
X(a, CALLBACK, SINGULAR, BYTES,    buf,               3)
#define vaccel_GenopArg_CALLBACK pb_default_field_callback
#define vaccel_GenopArg_DEFAULT NULL

#define vaccel_GenopRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   session_id,        1) \
X(a, CALLBACK, REPEATED, MESSAGE,  read_args,         2) \
X(a, CALLBACK, REPEATED, MESSAGE,  write_args,        3)
#define vaccel_GenopRequest_CALLBACK pb_default_field_callback
#define vaccel_GenopRequest_DEFAULT NULL
#define vaccel_GenopRequest_read_args_MSGTYPE vaccel_GenopArg
#define vaccel_GenopRequest_write_args_MSGTYPE vaccel_GenopArg

#define vaccel_GenopResult_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  write_args,        1)
#define vaccel_GenopResult_CALLBACK pb_default_field_callback
#define vaccel_GenopResult_DEFAULT NULL
#define vaccel_GenopResult_write_args_MSGTYPE vaccel_GenopArg

#define vaccel_GenopResponse_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (result,error,result.error),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (result,genop_result,result.genop_result),   2)
#define vaccel_GenopResponse_CALLBACK NULL
#define vaccel_GenopResponse_DEFAULT NULL
#define vaccel_GenopResponse_result_error_MSGTYPE vaccel_VaccelError
#define vaccel_GenopResponse_result_genop_result_MSGTYPE vaccel_GenopResult

extern const pb_msgdesc_t vaccel_GenopArg_msg;
extern const pb_msgdesc_t vaccel_GenopRequest_msg;
extern const pb_msgdesc_t vaccel_GenopResult_msg;
extern const pb_msgdesc_t vaccel_GenopResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define vaccel_GenopArg_fields &vaccel_GenopArg_msg
#define vaccel_GenopRequest_fields &vaccel_GenopRequest_msg
#define vaccel_GenopResult_fields &vaccel_GenopResult_msg
#define vaccel_GenopResponse_fields &vaccel_GenopResponse_msg

/* Maximum encoded size of messages (where known) */
/* vaccel_GenopArg_size depends on runtime parameters */
/* vaccel_GenopRequest_size depends on runtime parameters */
/* vaccel_GenopResult_size depends on runtime parameters */
/* vaccel_GenopResponse_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
