/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9-dev */

#include "genop.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(vaccel_GenopArg, vaccel_GenopArg, AUTO)


PB_BIND(vaccel_GenopRequest, vaccel_GenopRequest, AUTO)


PB_BIND(vaccel_GenopResult, vaccel_GenopResult, AUTO)


PB_BIND(vaccel_GenopResponse, vaccel_GenopResponse, AUTO)



