/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9-dev */

#ifndef PB_VACCEL_PROFILING_PB_H_INCLUDED
#define PB_VACCEL_PROFILING_PB_H_INCLUDED
#include <pb.h>
#include "error.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _vaccel_ProfilingRequest {
    uint32_t session_id;
} vaccel_ProfilingRequest;

typedef struct _vaccel_ProfRegion {
    pb_callback_t name;
    pb_callback_t samples;
} vaccel_ProfRegion;

typedef struct _vaccel_ProfRegion_Sample {
    uint64_t start;
    uint64_t time;
} vaccel_ProfRegion_Sample;

typedef struct _vaccel_ProfRegions {
    pb_callback_t timer;
} vaccel_ProfRegions;

typedef struct _vaccel_ProfilingResponse {
    bool has_result;
    vaccel_ProfRegions result;
} vaccel_ProfilingResponse;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define vaccel_ProfilingRequest_init_default     {0}
#define vaccel_ProfRegion_init_default           {{{NULL}, NULL}, {{NULL}, NULL}}
#define vaccel_ProfRegion_Sample_init_default    {0, 0}
#define vaccel_ProfRegions_init_default          {{{NULL}, NULL}}
#define vaccel_ProfilingResponse_init_default    {false, vaccel_ProfRegions_init_default}
#define vaccel_ProfilingRequest_init_zero        {0}
#define vaccel_ProfRegion_init_zero              {{{NULL}, NULL}, {{NULL}, NULL}}
#define vaccel_ProfRegion_Sample_init_zero       {0, 0}
#define vaccel_ProfRegions_init_zero             {{{NULL}, NULL}}
#define vaccel_ProfilingResponse_init_zero       {false, vaccel_ProfRegions_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define vaccel_ProfilingRequest_session_id_tag   1
#define vaccel_ProfRegion_name_tag               1
#define vaccel_ProfRegion_samples_tag            2
#define vaccel_ProfRegion_Sample_start_tag       1
#define vaccel_ProfRegion_Sample_time_tag        2
#define vaccel_ProfRegions_timer_tag             1
#define vaccel_ProfilingResponse_result_tag      1

/* Struct field encoding specification for nanopb */
#define vaccel_ProfilingRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   session_id,        1)
#define vaccel_ProfilingRequest_CALLBACK NULL
#define vaccel_ProfilingRequest_DEFAULT NULL

#define vaccel_ProfRegion_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   name,              1) \
X(a, CALLBACK, REPEATED, MESSAGE,  samples,           2)
#define vaccel_ProfRegion_CALLBACK pb_default_field_callback
#define vaccel_ProfRegion_DEFAULT NULL
#define vaccel_ProfRegion_samples_MSGTYPE vaccel_ProfRegion_Sample

#define vaccel_ProfRegion_Sample_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   start,             1) \
X(a, STATIC,   SINGULAR, UINT64,   time,              2)
#define vaccel_ProfRegion_Sample_CALLBACK NULL
#define vaccel_ProfRegion_Sample_DEFAULT NULL

#define vaccel_ProfRegions_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  timer,             1)
#define vaccel_ProfRegions_CALLBACK pb_default_field_callback
#define vaccel_ProfRegions_DEFAULT NULL
#define vaccel_ProfRegions_timer_MSGTYPE vaccel_ProfRegion

#define vaccel_ProfilingResponse_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  result,            1)
#define vaccel_ProfilingResponse_CALLBACK NULL
#define vaccel_ProfilingResponse_DEFAULT NULL
#define vaccel_ProfilingResponse_result_MSGTYPE vaccel_ProfRegions

extern const pb_msgdesc_t vaccel_ProfilingRequest_msg;
extern const pb_msgdesc_t vaccel_ProfRegion_msg;
extern const pb_msgdesc_t vaccel_ProfRegion_Sample_msg;
extern const pb_msgdesc_t vaccel_ProfRegions_msg;
extern const pb_msgdesc_t vaccel_ProfilingResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define vaccel_ProfilingRequest_fields &vaccel_ProfilingRequest_msg
#define vaccel_ProfRegion_fields &vaccel_ProfRegion_msg
#define vaccel_ProfRegion_Sample_fields &vaccel_ProfRegion_Sample_msg
#define vaccel_ProfRegions_fields &vaccel_ProfRegions_msg
#define vaccel_ProfilingResponse_fields &vaccel_ProfilingResponse_msg

/* Maximum encoded size of messages (where known) */
/* vaccel_ProfRegion_size depends on runtime parameters */
/* vaccel_ProfRegions_size depends on runtime parameters */
/* vaccel_ProfilingResponse_size depends on runtime parameters */
#define VACCEL_PROFILING_PB_H_MAX_SIZE           vaccel_ProfRegion_Sample_size
#define vaccel_ProfRegion_Sample_size            22
#define vaccel_ProfilingRequest_size             6

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
