/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9-dev */

#include "profiling.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(vaccel_ProfilingRequest, vaccel_ProfilingRequest, AUTO)


PB_BIND(vaccel_ProfRegion, vaccel_ProfRegion, AUTO)


PB_BIND(vaccel_ProfRegion_Sample, vaccel_ProfRegion_Sample, AUTO)


PB_BIND(vaccel_ProfRegions, vaccel_ProfRegions, AUTO)


PB_BIND(vaccel_ProfilingResponse, vaccel_ProfilingResponse, AUTO)



