/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9-dev */

#ifndef PB_VACCEL_RESOURCES_PB_H_INCLUDED
#define PB_VACCEL_RESOURCES_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _vaccel_CreateCaffeModelRequest {
    pb_callback_t prototxt;
    pb_callback_t binary_model;
    pb_callback_t labels;
} vaccel_CreateCaffeModelRequest;

typedef struct _vaccel_CreateTensorflowModelRequest {
    pb_callback_t model;
} vaccel_CreateTensorflowModelRequest;

typedef struct _vaccel_CreateTensorflowSavedModelRequest {
    pb_callback_t model_pb;
    pb_callback_t checkpoint;
    pb_callback_t var_index;
} vaccel_CreateTensorflowSavedModelRequest;

typedef struct _vaccel_CreateSharedObjRequest {
    pb_callback_t shared_obj;
} vaccel_CreateSharedObjRequest;

typedef struct _vaccel_CreateTorchSavedModelRequest {
    pb_callback_t model;
} vaccel_CreateTorchSavedModelRequest;

typedef struct _vaccel_CreateResourceRequest {
    pb_size_t which_model;
    union {
        vaccel_CreateTensorflowModelRequest tf;
        vaccel_CreateCaffeModelRequest caffe;
        vaccel_CreateTensorflowSavedModelRequest tf_saved;
        vaccel_CreateSharedObjRequest shared_obj;
        vaccel_CreateTorchSavedModelRequest torch_saved;
    } model;
} vaccel_CreateResourceRequest;

typedef struct _vaccel_CreateResourceResponse {
    int64_t resource_id;
} vaccel_CreateResourceResponse;

typedef struct _vaccel_RegisterResourceRequest {
    int64_t resource_id;
    uint32_t session_id;
} vaccel_RegisterResourceRequest;

typedef struct _vaccel_UnregisterResourceRequest {
    uint32_t session_id;
    int64_t resource_id;
} vaccel_UnregisterResourceRequest;

typedef struct _vaccel_DestroyResourceRequest {
    int64_t resource_id;
} vaccel_DestroyResourceRequest;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define vaccel_CreateCaffeModelRequest_init_default {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define vaccel_CreateTensorflowModelRequest_init_default {{{NULL}, NULL}}
#define vaccel_CreateTensorflowSavedModelRequest_init_default {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define vaccel_CreateSharedObjRequest_init_default {{{NULL}, NULL}}
#define vaccel_CreateTorchSavedModelRequest_init_default {{{NULL}, NULL}}
#define vaccel_CreateResourceRequest_init_default {0, {vaccel_CreateTensorflowModelRequest_init_default}}
#define vaccel_CreateResourceResponse_init_default {0}
#define vaccel_RegisterResourceRequest_init_default {0, 0}
#define vaccel_UnregisterResourceRequest_init_default {0, 0}
#define vaccel_DestroyResourceRequest_init_default {0}
#define vaccel_CreateCaffeModelRequest_init_zero {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define vaccel_CreateTensorflowModelRequest_init_zero {{{NULL}, NULL}}
#define vaccel_CreateTensorflowSavedModelRequest_init_zero {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define vaccel_CreateSharedObjRequest_init_zero  {{{NULL}, NULL}}
#define vaccel_CreateTorchSavedModelRequest_init_zero {{{NULL}, NULL}}
#define vaccel_CreateResourceRequest_init_zero   {0, {vaccel_CreateTensorflowModelRequest_init_zero}}
#define vaccel_CreateResourceResponse_init_zero  {0}
#define vaccel_RegisterResourceRequest_init_zero {0, 0}
#define vaccel_UnregisterResourceRequest_init_zero {0, 0}
#define vaccel_DestroyResourceRequest_init_zero  {0}

/* Field tags (for use in manual encoding/decoding) */
#define vaccel_CreateCaffeModelRequest_prototxt_tag 2
#define vaccel_CreateCaffeModelRequest_binary_model_tag 3
#define vaccel_CreateCaffeModelRequest_labels_tag 4
#define vaccel_CreateTensorflowModelRequest_model_tag 1
#define vaccel_CreateTensorflowSavedModelRequest_model_pb_tag 1
#define vaccel_CreateTensorflowSavedModelRequest_checkpoint_tag 2
#define vaccel_CreateTensorflowSavedModelRequest_var_index_tag 3
#define vaccel_CreateSharedObjRequest_shared_obj_tag 1
#define vaccel_CreateTorchSavedModelRequest_model_tag 1
#define vaccel_CreateResourceRequest_tf_tag      1
#define vaccel_CreateResourceRequest_caffe_tag   2
#define vaccel_CreateResourceRequest_tf_saved_tag 3
#define vaccel_CreateResourceRequest_shared_obj_tag 4
#define vaccel_CreateResourceRequest_torch_saved_tag 5
#define vaccel_CreateResourceResponse_resource_id_tag 1
#define vaccel_RegisterResourceRequest_resource_id_tag 1
#define vaccel_RegisterResourceRequest_session_id_tag 2
#define vaccel_UnregisterResourceRequest_session_id_tag 1
#define vaccel_UnregisterResourceRequest_resource_id_tag 2
#define vaccel_DestroyResourceRequest_resource_id_tag 1

/* Struct field encoding specification for nanopb */
#define vaccel_CreateCaffeModelRequest_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES,    prototxt,          2) \
X(a, CALLBACK, SINGULAR, BYTES,    binary_model,      3) \
X(a, CALLBACK, SINGULAR, BYTES,    labels,            4)
#define vaccel_CreateCaffeModelRequest_CALLBACK pb_default_field_callback
#define vaccel_CreateCaffeModelRequest_DEFAULT NULL

#define vaccel_CreateTensorflowModelRequest_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES,    model,             1)
#define vaccel_CreateTensorflowModelRequest_CALLBACK pb_default_field_callback
#define vaccel_CreateTensorflowModelRequest_DEFAULT NULL

#define vaccel_CreateTensorflowSavedModelRequest_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES,    model_pb,          1) \
X(a, CALLBACK, SINGULAR, BYTES,    checkpoint,        2) \
X(a, CALLBACK, SINGULAR, BYTES,    var_index,         3)
#define vaccel_CreateTensorflowSavedModelRequest_CALLBACK pb_default_field_callback
#define vaccel_CreateTensorflowSavedModelRequest_DEFAULT NULL

#define vaccel_CreateSharedObjRequest_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES,    shared_obj,        1)
#define vaccel_CreateSharedObjRequest_CALLBACK pb_default_field_callback
#define vaccel_CreateSharedObjRequest_DEFAULT NULL

#define vaccel_CreateTorchSavedModelRequest_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES,    model,             1)
#define vaccel_CreateTorchSavedModelRequest_CALLBACK pb_default_field_callback
#define vaccel_CreateTorchSavedModelRequest_DEFAULT NULL

#define vaccel_CreateResourceRequest_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (model,tf,model.tf),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (model,caffe,model.caffe),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (model,tf_saved,model.tf_saved),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (model,shared_obj,model.shared_obj),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (model,torch_saved,model.torch_saved),   5)
#define vaccel_CreateResourceRequest_CALLBACK NULL
#define vaccel_CreateResourceRequest_DEFAULT NULL
#define vaccel_CreateResourceRequest_model_tf_MSGTYPE vaccel_CreateTensorflowModelRequest
#define vaccel_CreateResourceRequest_model_caffe_MSGTYPE vaccel_CreateCaffeModelRequest
#define vaccel_CreateResourceRequest_model_tf_saved_MSGTYPE vaccel_CreateTensorflowSavedModelRequest
#define vaccel_CreateResourceRequest_model_shared_obj_MSGTYPE vaccel_CreateSharedObjRequest
#define vaccel_CreateResourceRequest_model_torch_saved_MSGTYPE vaccel_CreateTorchSavedModelRequest

#define vaccel_CreateResourceResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT64,    resource_id,       1)
#define vaccel_CreateResourceResponse_CALLBACK NULL
#define vaccel_CreateResourceResponse_DEFAULT NULL

#define vaccel_RegisterResourceRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT64,    resource_id,       1) \
X(a, STATIC,   SINGULAR, UINT32,   session_id,        2)
#define vaccel_RegisterResourceRequest_CALLBACK NULL
#define vaccel_RegisterResourceRequest_DEFAULT NULL

#define vaccel_UnregisterResourceRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   session_id,        1) \
X(a, STATIC,   SINGULAR, INT64,    resource_id,       2)
#define vaccel_UnregisterResourceRequest_CALLBACK NULL
#define vaccel_UnregisterResourceRequest_DEFAULT NULL

#define vaccel_DestroyResourceRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT64,    resource_id,       1)
#define vaccel_DestroyResourceRequest_CALLBACK NULL
#define vaccel_DestroyResourceRequest_DEFAULT NULL

extern const pb_msgdesc_t vaccel_CreateCaffeModelRequest_msg;
extern const pb_msgdesc_t vaccel_CreateTensorflowModelRequest_msg;
extern const pb_msgdesc_t vaccel_CreateTensorflowSavedModelRequest_msg;
extern const pb_msgdesc_t vaccel_CreateSharedObjRequest_msg;
extern const pb_msgdesc_t vaccel_CreateTorchSavedModelRequest_msg;
extern const pb_msgdesc_t vaccel_CreateResourceRequest_msg;
extern const pb_msgdesc_t vaccel_CreateResourceResponse_msg;
extern const pb_msgdesc_t vaccel_RegisterResourceRequest_msg;
extern const pb_msgdesc_t vaccel_UnregisterResourceRequest_msg;
extern const pb_msgdesc_t vaccel_DestroyResourceRequest_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define vaccel_CreateCaffeModelRequest_fields &vaccel_CreateCaffeModelRequest_msg
#define vaccel_CreateTensorflowModelRequest_fields &vaccel_CreateTensorflowModelRequest_msg
#define vaccel_CreateTensorflowSavedModelRequest_fields &vaccel_CreateTensorflowSavedModelRequest_msg
#define vaccel_CreateSharedObjRequest_fields &vaccel_CreateSharedObjRequest_msg
#define vaccel_CreateTorchSavedModelRequest_fields &vaccel_CreateTorchSavedModelRequest_msg
#define vaccel_CreateResourceRequest_fields &vaccel_CreateResourceRequest_msg
#define vaccel_CreateResourceResponse_fields &vaccel_CreateResourceResponse_msg
#define vaccel_RegisterResourceRequest_fields &vaccel_RegisterResourceRequest_msg
#define vaccel_UnregisterResourceRequest_fields &vaccel_UnregisterResourceRequest_msg
#define vaccel_DestroyResourceRequest_fields &vaccel_DestroyResourceRequest_msg

/* Maximum encoded size of messages (where known) */
/* vaccel_CreateCaffeModelRequest_size depends on runtime parameters */
/* vaccel_CreateTensorflowModelRequest_size depends on runtime parameters */
/* vaccel_CreateTensorflowSavedModelRequest_size depends on runtime parameters */
/* vaccel_CreateSharedObjRequest_size depends on runtime parameters */
/* vaccel_CreateTorchSavedModelRequest_size depends on runtime parameters */
/* vaccel_CreateResourceRequest_size depends on runtime parameters */
#define VACCEL_RESOURCES_PB_H_MAX_SIZE           vaccel_RegisterResourceRequest_size
#define vaccel_CreateResourceResponse_size       11
#define vaccel_DestroyResourceRequest_size       11
#define vaccel_RegisterResourceRequest_size      17
#define vaccel_UnregisterResourceRequest_size    17

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
