/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9-dev */

#include "resources.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(vaccel_CreateCaffeModelRequest, vaccel_CreateCaffeModelRequest, AUTO)


PB_BIND(vaccel_CreateTensorflowModelRequest, vaccel_CreateTensorflowModelRequest, AUTO)


PB_BIND(vaccel_CreateTensorflowSavedModelRequest, vaccel_CreateTensorflowSavedModelRequest, AUTO)


PB_BIND(vaccel_CreateSharedObjRequest, vaccel_CreateSharedObjRequest, AUTO)


PB_BIND(vaccel_CreateTorchSavedModelRequest, vaccel_CreateTorchSavedModelRequest, AUTO)


PB_BIND(vaccel_CreateResourceRequest, vaccel_CreateResourceRequest, AUTO)


PB_BIND(vaccel_CreateResourceResponse, vaccel_CreateResourceResponse, AUTO)


PB_BIND(vaccel_RegisterResourceRequest, vaccel_RegisterResourceRequest, AUTO)


PB_BIND(vaccel_UnregisterResourceRequest, vaccel_UnregisterResourceRequest, AUTO)


PB_BIND(vaccel_DestroyResourceRequest, vaccel_DestroyResourceRequest, AUTO)



