/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9-dev */

#include "session.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(vaccel_CreateSessionRequest, vaccel_CreateSessionRequest, AUTO)


PB_BIND(vaccel_UpdateSessionRequest, vaccel_UpdateSessionRequest, AUTO)


PB_BIND(vaccel_DestroySessionRequest, vaccel_DestroySessionRequest, AUTO)


PB_BIND(vaccel_CreateSessionResponse, vaccel_CreateSessionResponse, AUTO)



