/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9-dev */

#include "tensorflow.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(vaccel_TensorflowModelLoadRequest, vaccel_TensorflowModelLoadRequest, AUTO)


PB_BIND(vaccel_TensorflowModelLoadResponse, vaccel_TensorflowModelLoadResponse, AUTO)


PB_BIND(vaccel_TensorflowModelUnloadRequest, vaccel_TensorflowModelUnloadRequest, AUTO)


PB_BIND(vaccel_TensorflowModelUnloadResponse, vaccel_TensorflowModelUnloadResponse, AUTO)


PB_BIND(vaccel_TFTensor, vaccel_TFTensor, AUTO)


PB_BIND(vaccel_TFNode, vaccel_TFNode, AUTO)


PB_BIND(vaccel_TensorflowModelRunRequest, vaccel_TensorflowModelRunRequest, AUTO)


PB_BIND(vaccel_InferenceResult, vaccel_InferenceResult, AUTO)


PB_BIND(vaccel_TensorflowModelRunResponse, vaccel_TensorflowModelRunResponse, AUTO)




