/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9-dev */

#include "torch.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(vaccel_TorchTensor, vaccel_TorchTensor, AUTO)


PB_BIND(vaccel_TorchJitloadForwardRequest, vaccel_TorchJitloadForwardRequest, AUTO)


PB_BIND(vaccel_TorchJitloadForwardResult, vaccel_TorchJitloadForwardResult, AUTO)


PB_BIND(vaccel_TorchJitloadForwardResponse, vaccel_TorchJitloadForwardResponse, AUTO)





